#!/bin/bash
source /etc/profile

# brewなどでインストールしたコマンドを優先
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/node_modules/bin"

# 分割した設定ファイルの読み込み
shopt -s nullglob
for f in ~/.bash.d/*.sh ~/dotfiles/bash/*.sh; do
  echo loading "$f" >&2
  source "$f"
done
shopt -u nullglob

export PATH="$HOME/bin:$PATH"

# Lang
export LAMG=en_US.UTF-8
export LC_TIME=en_US.UTF-8
# vimをカラフルにする
export TERM=xterm-256color

# Ctrl+S を無効
for h in "omoto-xubuntu" "m3-2015mac03.office.so-netm3.com"; do
  if [ "$(hostname)" = "$h" ]; then
    stty stop undef
  fi
done

alias cdpwd='cd $(pwd -P)'
alias gr='egrep --ignore-case --color=auto --line-number --with-filename --binary-files=without-match'
alias diff2html='~/dotfiles/diff2html/diff2html.py'
alias html2browse='~/dotfiles/diff2html/html2browse.py'
alias d2b='diff2html | html2browse'
alias nob='diff2html | html2browse'
alias escape='python ~/dotfiles/escape.py'
alias mime='~/dotfiles/mime.py'

function te {
  cat - | ~/dotfiles/bin/save-tempfile -c gvim "$@"
}

alias colorize='python3 ~/dotfiles/colorize.py'
alias findall='~/dotfiles/findall'

# 存在するファイルのみをフィルタリング
function fexists() {
  cat - | while read line; do
    if [ -e "${line}" ]; then
      echo "${line}"
    fi
  done
}

function title() {
  echo -en "\033]0;$*\007"
}

# コマンド履歴の共有
function share_history {
  history -a
  history -c
  history -r
}

PROMPT_COMMAND='share_history;title "${USER}@${HOSTNAME%%.*}"'
shopt -u histappend
export HISTSIZE=10000
export HISTTIMEFORMAT='%Y-%m-%dT%T%z '

# シェルの細かい設定
set -o emacs
set mark-directories on
set show-all-if-ambiguous on
set visible-status on

# pbcopy
if ! which pbcopy &> /dev/null; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi

function ge() {
  ~/dotfiles/open-gvim "$(cat - | sed -e 's/\(^.*\):[[:digit:]]\+:.*/\1/' | sort -u)"
}

clean-meld() {
  paths=$(find . \
    -name '*.BACKUP.*' -or \
    -name '*.BASE.*'   -or \
    -name '*.LOCAL.*'  -or \
    -name '*.REMOTE.*'
  )

  if [ -z "${paths[@]}" ]; then
    return 0
  fi

  for f in "${paths[@]}"; do
    echo "$f"
  done

  echo -n "delete these files? [y/N] " >&2
  read input
  if [ "${input}" = "y" ]; then
    rm "${paths[@]}" || return 1
    return 0
  fi
  return 2
}


if which fzf &> /dev/null; then
  _replace_by_history() {
    local sed=sed
    if which gsed &> /dev/null; then
      sed=gsed
    fi
    local l
    l=$(HISTTIMEFORMAT='' history | sort -k1,1nr | $sed -e 's/^[[:space:]]*[0-9]\+[[:space:]]*//' | uniq-everseen | fzf --query "$READLINE_LINE")
    READLINE_LINE="$l"
    READLINE_POINT=${#l}
  }

  _find_and_edit() {
    fzf | xargs gvim
  }

  bind -x '"\C-r": _replace_by_history'
  bind    '"\C-xr": reverse-search-history'
  bind -x '"`": _find_and_edit'

  # fzf
  export FZF_DEFAULT_OPTS="--no-sort -i --multi --reverse --cycle --prompt='QUERY> ' --inline-info --color=16"

  p() {
    local f;
    f="$({ echo -n 'Downloads'; find "$HOME/Documents/" -maxdepth 1 -type 'd' | sed -e 's|.*/||' | sort ; } | fzf)"
    if [ -z "$f" ]; then
      return 1
    fi
    if [ "$f" = "Downloads" ]; then
      cd "$HOME/Downloads"
      return
    fi
    cd "${HOME}/Documents/$f"
  }

  d() {
    local f
    f="$({ echo '..'; find . -maxdepth 1 -mindepth 1 -type 'd' | grep -v "\/\." | sed -e 's|^./||' -e 's|$|/|' ; } | fzf)"
    if [ -z "$f" ]; then
      return 1
    fi
    cd "$f"
  }
fi

export PATH=$PATH:/usr/local/haskell/ghc-7.8.3-x86_64/bin/

yaml2json() {
  ruby -ryaml -rjson -e "print YAML.load(STDIN).to_json" -
}

json2yaml() {
  ruby -ryaml -rjson -e "print JSON.load(STDIN).to_yaml" -
}

export PATH=$PATH:~/.cabal/bin
export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/dotfiles/bin

alias stripcolor="perl -pe 's/\e\[?.*?[\@-~]//g'"

fe() {
  find . -name "${1:-*}" | fzf | xargs gvim
}

whichvi() {
  local f
  if [ -n "$1" ]; then
    which -a "$1" | fzf | xargs gvim
  else
    paths=($(echo "$PATH" | tr ':' ' '))
    find "${paths[@]}" -type f -perm +111 2>/dev/null | fzf | xargs gvim
  fi
}
alias ..='. ~/.bashrc'
alias ...='gvim ~/.bashrc'

if which gnome-open &> /dev/null; then
  alias open=gnome-open
fi
