#!/bin/bash
use_python() {
  local version=$1
  local d
  d="$PYENV_ROOT/versions/$version/bin"
  if ! [ -d "$d" ]; then
    return 1
  fi
  PATH_add "$d"
}

# pyenv shell 2.7.11 3.5.1 3.2.6 3.3.6 3.4.4
