#!/bin/bash
. ~/dotfiles/direnv/docker.direnvrc
. ~/dotfiles/direnv/java.direnvrc

use_python() {
  local version=$1
  local d
  d="$PYENV_ROOT/versions/$version/bin"
  if ! [ -d "$d" ]; then
    return 1
  fi
  PATH_add "$d"
}

# pyenv shell 2.7.11 3.5.1 3.2.6 3.3.6 3.4.4

use_venv() {
  if [ "$#" -ne 1 ]; then
    echo "usage: use venv VERSION" >&2
    return 1
  fi

  local version=$1
  local dir='.venv'
  if [ ! -d "$dir" ]; then
    echo "$dir/ is not found. creating $dir/ ."
    local python="$PYENV_ROOT/versions/$version/bin/python" 
    "$python" -m venv --system-site-packages "$dir"
  else
    echo "$dir/ already exists."
  fi

  source "$dir/bin/activate"
}
