#!/usr/bin/env python3
import argparse
import re
import sys

parser = argparse.ArgumentParser()
parser.add_argument('pattern', type=str)
parser.add_argument('files', nargs='*', type=argparse.FileType('r'),
                    default=sys.stdin)

args = parser.parse_args()

regex = re.compile(args.pattern)
findall = regex.findall
key = 0 if not regex.groups else 1
for line in itertools.chain.from_iterable(args.files):
    for m in regex.finditer(line):
        print(m.group(key))
