#!/bin/bash
vim --serverlist 2> /dev/null \
  | grep GVIM > /dev/null && vim -g --servername GVIM --remote-expr 'foreground()' || vim --servername GVIM -g 2> /dev/null

if [ $# -eq 0 ]; then
  exit
fi

args=($(echo "$1" | sed -e "s|\(.*\):\([[:digit:]]\+\)|+\2 \1|"))
shift
for f in "$@"; do
  args=(${args[@]} $(echo "$f" | sed -e "s|\(.*\):\([[:digit:]]\+\)|\1|"))
done

vim -g --servername GVIM --remote-tab-silent ${args[@]}
